language: node_js

cache: npm

notifications:
  email: false

node_js:
  - '12'
  - '10'
  - '11'
  - '8'
  - 'node'

script:
  - npm run test:prod && npm run build

jobs:
  include:
    - stage: gh-pages-deploy
      script: npm run generate-docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: ./docs
        github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          tags: true
    - stage: npm-release-deploy
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN # Set in the settings page of your repository, as a secure variable
        on:
          tags: true
